apiVersion: v1
kind: Secret
metadata:
  name: cure-backend-secret
  namespace: cure
  labels:
    app.kubernetes.io/name: cure-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cure-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://cure_app:REPLACE_PASSWORD@replace-rds-endpoint.eu-central-1.rds.amazonaws.com:5432/cure_db"
  JWT_SECRET: "replace_with_long_random_secret_at_least_32_chars"