apiVersion: v1
kind: ServiceAccount
metadata:
  name: cure-backend-sa
  namespace: cure
  labels:
    app.kubernetes.io/name: cure-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cure-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::092131851744:role/replace-cure-backend-irsa-role
automountServiceAccountToken: true